#!/usr/bin/env bash
# This scripts print "Best School" 10 times
# but "Hi" on the 9th interation

count=1

while ((count < 10))
do
	if ((count == 9));
	then
		echo "Best School"
		echo "Hi"
	fi

	echo "Best School"

	((count++))
done
