#!/usr/bin/env bash

count=1

while ((count <= 10))
do
	if ((count == 4)); then
		echo "bad luck"
	elif ((count == 8)); then
		echo "good luck"
	else
		echo "Best School"
	fi

	count=$((count + 1))
done
